### Request all users
GET http://localhost:6007/api/users HTTP/1.1
Accept: application/json

### Request a single user
GET http://localhost:6007/api/users/user@mail.com HTTP/1.1
Accept: application/json

### Add new user
POST http://localhost:6007/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "daniel",
    "email": "user@mail.com",
    "phone": "5123456",
    "city": "Cologne",
    "experience": "professional",
    "password": "ilovedogs123",
    "photo": "string"
}

### Correct login
POST http://localhost:6007/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "user@mail.com",
    "password": "ilovedogs123"
}

### Incorrect login
POST http://localhost:6007/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "bla@mail.com",
    "password": "wrong"
}
